[package]
name = "rtmcli"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todotxt = { path = "../todotxt" }
chrono = "0.4.31"
clap = { version = "4.0", features = ["derive"] }
uuid = "1.18.1"
